version: 0.2
env:
  shell: bash
  git-credential-helper: yes
  variables:
    TERRAFORM_VERSION: 1.2.8
    CHECKOV_VERSION: 2.2.125
    TFLINT_VERSION: 0.39.1
    TFLINT_AWS_RULESET_VERSION: 0.15.0
phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo Entered the INSTALL phase
      - yum update -y
      - yum install jq git -y -q
      - yum install -y -q ca-certificates curl less unzip py-pip && rm -rf /var/cache/yum/*
      - pip install pip --upgrade
      - aws configure set default.region $AWS_DEFAULT_REGION
      - mkdir -p ~/.tflint.d/plugins
      # install Terraform, Checkov and TFLint
      - >
        pushd /usr/local/bin &&
        curl https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip -o terraform_${TERRAFORM_VERSION}_linux_amd64.zip &&
        unzip terraform_${TERRAFORM_VERSION}_linux_amd64.zip &&
        rm terraform_${TERRAFORM_VERSION}_linux_amd64.zip
  pre_build:
    commands:
      - echo "====================="
      - echo Entered the pre_build phase...
      - terraform --version
  build:
    commands:
      - echo "====================="
      - cd $CODEBUILD_SRC_DIR
      - mkdir -p $CODEBUILD_SRC_DIR/reports
      - echo ENV_NAME=$ENV_NAME
      - pwd
      - ls -ltr
      - scripts/terraform_apply.sh "infrastructure/lambda_iac" $ENV_NAME
  post_build:
    commands:
      - echo "====================="
      - echo Entered the post_build phase...
      # - >
      #   rm -rf .terraform/ &&
      #   rm -rf .external_modules/
# reports:
#   checkov-reports:
#     files:
#       - "./reports/*.xml"
#     file-format: "JUNITXML"
artifacts:
    files:
      - '**/*'